version: "3.9"

networks:
  internal:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  rest:
    build: core/rest
    environment:
      REDIS_HOST: "172.20.0.2:6379"
      ROCKET_ADDRESS: 0.0.0.0
    env_file:
      - .rest.env
    ports:
      - 8880:8000
    networks:
      internal:
        ipv4_address: 172.20.0.4
      default:
    depends_on:
      - "redis"
    restart: unless-stopped
  gateway:
    build: core/gateway
    environment:
      REDIS_HOST: "172.20.0.2:6379"
    ports:
      - 8881:3030
    networks:
      internal:
        ipv4_address: 172.20.0.3
      default:
    depends_on:
      - "redis"
    restart: unless-stopped
  redis:
    image: redislabs/rejson:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      internal:
        ipv4_address: 172.20.0.2
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --dir /data --save 900 1 --save 300 5 --save 60 15
volumes:
  redis_data: